#
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "lastname" : "berk",
    "firstname" : "blab",
    "phone" : "0909090909",
    "address" : "8 graance",
    "city" : "paris",
    "country" : "france",
    "email" : "blabla@gmail.com",
    "password" : "Hayamottal555/",
    "zipcode" : "75019",
    "sex" : "WOMAN"
}

### CREATE PRO
POST http://localhost:3003/user/pro/create
Content-Type: application/json

{
    "lastname" : "coco",
    "firstname" : "coco",
    "phone" : "0140161716",
    "address" : "8 rue de romainville",
    "city" : "paris",
    "country" : "france",
    "email" : "donc@gmail.com",
    "password" : "Hayamottal555/",
    "zipcode" : "75019",
    "sex" : "WOMAN",
    "role" : "PRO",
    "job": "pediatre"
}

### FAUX PASS
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "coco"
}

### FAUX MAIL
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamsottal@gmail.com",
    "password" : "coco"
}


### FAUX TOUT
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamodgbusjkgdbttal@gmail.com",
    "password" : "bla"
}

### 
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "Hayamottal555/"
}

### 
GET http://localhost:3003/user/current



### CONNEXION ADMIN
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "crechelesphoenix@gmail.com",
    "password" : "Hayamottal555/"
}



### CONNEXION PRO
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "Hayamottal555/"
}


### 
GET http://localhost:3003/admin/pro


### 
GET http://localhost:3003/admin/demandes


### GET PRO Moussiamottal@gmail.com
GET http://localhost:3003/admin/pro/628be114daaf25d16d391487
content-type: application/json


### GET PARENT kejlerj@gmail.com
GET http://localhost:3003/admin/parent/628be155fe616596c4795e3e


content-type: application/json
### SUPPRIMER UN PRO moussiamottal@gmail.com
DELETE http://localhost:3003/admin/628be114daaf25d16d391487


### SUPPRIMER UN PARENT kejlerj@gmail.com
DELETE http://localhost:3003/admin/628be155fe616596c4795e3e


###
PUT http://localhost:8000/admin/628be114daaf25d16d391487
content-type: application/json
{
    "activatedByAdmin": false
}

# ### 
# GET http://localhost:3003/pro/disponibilite


### 
DELETE http://localhost:3003/session



#### 
POST http://localhost:3003/pro/dispo/update
Content-Type: application/json
{
   "id_pro": "629605afae305793e55b128d",
   "isDisponible" : true
}



### CONNEXION PARENT
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "moussiamottal@gmail.com",
    "password" : "Hayamottal555/"
}


### get historique
GET http://localhost:3003/user/historique




### CONNEXION PRO
POST http://localhost:3003/session
Content-Type: application/json

{
    "email" : "bonjour@gmail.com",
    "password" : "Hayamottal555/"
}



###  GET DEMANDE
GET http://localhost:3003/admin/demandes


###  GET DEMANDE
GET http://localhost:3003/admin/demandesFini



###  GET DEMANDE
GET http://localhost:3003/pro/getDemandes

###  GET DEMANDE
GET http://localhost:3003/pro/getProDisponible