#
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "lastname" : "berk",
    "firstname" : "blab",
    "phone" : "0909090909",
    "address" : "8 graance",
    "city" : "paris",
    "country" : "france",
    "email" : "blabla@gmail.com",
    "password" : "Hayamottal555/",
    "zipcode" : "75019",
    "sex" : "WOMAN"
}
